server:
  port: 8088
mct:
  facilities-bundle-path: /app/config/facilities-bundle.json
hapi:
  fhir:
    fhir_version: R4
    package_server_url: https://packages.simplifier.net/
    terminology_server_url: http://tx.fhir.org/r4/
    install_transitive_ig_dependencies: false
    require_profile_for_validation: true
    implementationguides:
      qicore_6_0_0:
        url: https://hl7.org/fhir/us/qicore/STU6/package.tgz
        name: hl7.fhir.us.qicore
        version: 6.0.0
      uscore_6_1_0:
        url: http://hl7.org/fhir/us/core/STU6.1/package.tgz
        name: hl7.fhir.us.core
        version: 6.1.0
